version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tintot_postgres
    restart: always
    environment:
      POSTGRES_DB: tintotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: tintot_api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tintotdb;Username=postgres;Password=123456
    ports:
      - "5000:8080"

volumes:
  pgdata: