services:
  db:
    image: postgres:16
    container_name: tintot_postgres
    restart: always
    environment:
      POSTGRES_DB: tintotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: tintot_redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tintot_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tintotdb;Username=postgres;Password=123456
    ports:
      - "5000:8080"

volumes:
  pgdata: